### ISSUE TITLE
Why does NTR require a *proprietary* blob to run?

### ISSUE THREAD

**Issue by KashiToxicBlood** [44670/BootNTR#65]
BootNTR's cia is entirely free and open for anyone to modify or use yet the actual binary it reads off is a blob which cannot be changed, why not free up the blob or open up the software? I would love to try using this but I wont start unless it's fully free'd up or open.
Not to mention the debugger and video stream is also closed up and is exclusive to the Windows OS, what about people on GNU (Linux) ?

**Comment by 44670** [comment]
Please stop opening issues like this, I am tired to close them.

The Issue Tracker on Github is generally tracking bugs or new features for developers, I think it is probably not a place for arguing your opinions.

**Comment by profi200** [comment]
I'm not a huge fan of closed source myself but for example if it would be open source we had online cheaters long before Brickway all over the place. NTR CFW disables WiFi intentional so you can only cheat offline. Imho that is the right decision because there are so much online cheater dicks around who don't give a fuck if they ruin the fun for others.

Besides that it is the authors decision to make it open source or not but this is just my 2 cents. Not gonna comment further because this is really not the place to argue.

**Comment by Margen67** [comment]
@profi200 Because there aren't already cheaters online?

**Comment by profi200** [comment]
There is only Brickway users right now. They can go fuck themself. Otherwise there is only NTR CFW which disables online if you use per game plugins and i think that was the right decision to do.

Unless there is an alternative to it which can change memory of every process while online i think it is still a valid reason to keep it closed source for exactly this. And then it is still the decision of the author if he wants to make it open source. If he uses no GPL'd source or libs in any form there is no way to force it.

**Comment by izzy420** [comment]
@profi200  Except online cheating does work with NTR, there was literally a thread about MK7 where the guy made Speed codes up to 1000CC  and they were used online they shortly got taken down by OP.
Its not the case the cheats dont work online its more of the case people dont make them or still believe they dont or the fact its so minimal so one notices.
