### ISSUE TITLE
Write command

### ISSUE THREAD

**Issue by TheMrDew** [44670/BootNTR#75]
Before I started remoteplay, I used the write command to keep the WiFi from turning off.  I then went to poke money alpha Sapphire to do a test of that game.  When I wanted to play online, I kept getting communication errors.  Here is a link to the video I took with ntr of pokemon (46:26): https://www.youtube.com/watch?v=WR8im083Cos

**Comment by ApacheThunder** [comment]
FYI, if you intend to use Pokemon ORAS online, you do not need the write command. Simply having the game connect online restores video streaming. You only need to use the command for singleplayer only games or games that you can't connect online due to not having updated patch or being on outdated firmware.
